version: 0.1

environment_variables:
    plaintext:
        S3_BUCKET: "myapp-angularbuck"
        BUILD_ENV: "prod"
        BUILD_FOLDER: "dist"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli@19.2.7
    build:
        commands:
            - echo Build started for $BUILD_ENV on `date`
            - node -v
            - npm -v
            - ng build
            - echo Build completed…
    post_build:
         commands:
            - echo Pre-Build started on `date`
            - aws s3 sync ./dist s3://myapp-angularbuck
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`

artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
