version: 0.2

env:
  variables:
    S3_BUCKET: "angular-bucket-1234"
    BUILD_ENV: "prod"
    BUILD_FOLDER: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli@19.2.7

  build:
    commands:
      - echo Build started for $BUILD_ENV on `date`
      - node -v
      - npm -v
      - ng build --configuration=$BUILD_ENV
      - echo Build completed…

  post_build:
    commands:
      - echo Zipping build output...
      - cd $BUILD_FOLDER
      - ZIP_NAME=angular-build.zip
      - zip -r ../$ZIP_NAME .
      - cd ..
      - echo Uploading $ZIP_NAME to S3...
      - aws s3 cp $ZIP_NAME s3://$S3_BUCKET/$ZIP_NAME
     

artifacts:
  files:
    - angular-build.zip
